# Generated by Django 4.2.24 on 2025-09-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='register',
        ),
    ]
